import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";

const myFont = localFont({
  src: [
    {
      path: "../public/fonts/grift-regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/grift-blackitalic.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/fonts/grift-bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/grift-bolditalic.otf",
      weight: "700",
      style: "italic",
    },
    {
      path: "../public/fonts/grift-extrabold.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../public/fonts/grift-extralight.otf",
      weight: "200",
      style: "normal",
    },
  ],
  variable: "--font-grift",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Converso",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={myFont.variable} suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute={"class"}
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
